### ISSUE TITLE
How to use getReactElement() when property's name  in props contains "-"

### ISSUE THREAD

**Issue by CNFeffery** [repetere/jsonx#299]
such as 'data-dash-is-loading':
![image](https://user-images.githubusercontent.com/49147660/125617468-efd97880-8678-4bab-99b0-97114e8f3231.png)

**Comment by yawetse** [comment]
Hi @CNFeffery,

Apologies for taking so long to respond to this. You should be able to just use quotes around the property name, e.g. `"data-is-loading"`

I tested that out and it works, e.g.:
![image](https://user-images.githubusercontent.com/1192414/148973648-d95e4500-5479-419a-bc3a-ef0b1b1293ce.png)
![image](https://user-images.githubusercontent.com/1192414/148973734-177ab52e-5fb2-4009-920d-91b3d6a830bb.png)
![image](https://user-images.githubusercontent.com/1192414/148973797-994e5ecf-7d34-4faf-a702-5393bac724c3.png)
